# lover528/Script - Quantumult X 重写资源
# 用法：重写 → 规则资源 → 添加本文件 raw 链接并启用

^https:\/\/gate-obt\.nqf\.qq\.com url script-request-header https://raw.githubusercontent.com/lover528/Script/master/farm-code.js

hostname = gate-obt.nqf.qq.com
